name: React basic demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}--whatever--${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
          restore-key: |
            ${{ runner.os }}--whatever--
            ${{ runner.os }}--

      - name: Install packages
        run: npm install

      - name: Run tests
        run: npm test

      - name: Linting
        run: npm run lint

      - name: Building
        run: npm run build

      - name: Deploying to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
